name: Test
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  test_ruby_and_rails_versions:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        rails:
          - "4.2"
          - "5.0"
          - "5.1"
          - "5.2"
          - "6.0"
          - "6.1"
          - "7.0"

        ruby:
          - "2.4"
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"

        include:
          - rails: "4.2"
            bundler: "1.17.3"

        exclude:
          - rails: "4.2"
            ruby: "2.7"

          - rails: "4.2"
            ruby: "3.0"

          - rails: "5.0"
            ruby: "3.0"

          - rails: "5.1"
            ruby: "3.0"

          - rails: "5.2"
            ruby: "3.0"

          - rails: "6.0"
            ruby: "2.4"

          - rails: "6.1"
            ruby: "2.4"

          - rails: "7.0"
            ruby: "2.4"

          - rails: "7.0"
            ruby: "2.5"

          - rails: "7.0"
            ruby: "2.6"

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/spec/gemfiles/Gemfile.rails-${{ matrix.rails }}

    steps:
      - uses: actions/checkout@v2

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: "${{ matrix.bundler }}"
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
